import { Button } from "@/components/ui/button";
import { Database, Sparkles, BarChart3, Zap } from "lucide-react";
import { Link } from "react-router-dom";

const Landing = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b border-border">
        <div className="container mx-auto px-6 py-4 flex items-center justify-between">
          <div className="flex items-center gap-2">
            <Database className="h-6 w-6 text-primary" />
            <span className="text-xl font-semibold">DB RAG Analytics</span>
          </div>
          <Link to="/workspace">
            <Button variant="outline">Sign In</Button>
          </Link>
        </div>
      </header>

      {/* Hero Section */}
      <main className="container mx-auto px-6 py-20">
        <div className="max-w-4xl mx-auto text-center space-y-8">
          <div className="inline-flex items-center gap-2 px-4 py-2 rounded-full bg-primary/10 text-primary text-sm font-medium">
            <Sparkles className="h-4 w-4" />
            AI-Powered Database Analytics
          </div>
          
          <h1 className="text-5xl md:text-6xl font-bold tracking-tight">
            Ask Questions,
            <br />
            <span className="text-primary">Get SQL Answers</span>
          </h1>
          
          <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
            Upload your database schema and ask questions in plain English. Our AI generates SQL queries, 
            executes them, and visualizes the results—all in seconds.
          </p>

          <div className="flex items-center justify-center gap-4 pt-4">
            <Link to="/workspace">
              <Button size="lg" className="text-lg px-8">
                Get Started
              </Button>
            </Link>
            <Button size="lg" variant="outline" className="text-lg px-8">
              View Demo
            </Button>
          </div>
        </div>

        {/* Features Grid */}
        <div className="grid md:grid-cols-3 gap-8 mt-24 max-w-5xl mx-auto">
          <div className="p-8 rounded-2xl bg-card border border-border space-y-3">
            <div className="h-12 w-12 rounded-xl bg-primary/10 flex items-center justify-center">
              <Database className="h-6 w-6 text-primary" />
            </div>
            <h3 className="text-xl font-semibold">Schema Understanding</h3>
            <p className="text-muted-foreground">
              Automatically extracts and indexes your database schema, tables, columns, and relationships.
            </p>
          </div>

          <div className="p-8 rounded-2xl bg-card border border-border space-y-3">
            <div className="h-12 w-12 rounded-xl bg-accent/10 flex items-center justify-center">
              <Sparkles className="h-6 w-6 text-accent" />
            </div>
            <h3 className="text-xl font-semibold">Natural Language Queries</h3>
            <p className="text-muted-foreground">
              Ask questions in plain English and get accurate SQL queries generated by AI.
            </p>
          </div>

          <div className="p-8 rounded-2xl bg-card border border-border space-y-3">
            <div className="h-12 w-12 rounded-xl bg-chart-2/10 flex items-center justify-center">
              <BarChart3 className="h-6 w-6 text-chart-2" />
            </div>
            <h3 className="text-xl font-semibold">Visual Analytics</h3>
            <p className="text-muted-foreground">
              Automatically generates charts and visualizations from your query results.
            </p>
          </div>
        </div>

        {/* CTA Section */}
        <div className="mt-24 p-12 rounded-3xl bg-gradient-to-br from-primary/10 via-accent/5 to-transparent border border-border">
          <div className="max-w-2xl mx-auto text-center space-y-6">
            <div className="h-16 w-16 mx-auto rounded-2xl bg-primary flex items-center justify-center">
              <Zap className="h-8 w-8 text-primary-foreground" />
            </div>
            <h2 className="text-3xl font-bold">Ready to start analyzing?</h2>
            <p className="text-lg text-muted-foreground">
              Upload your SQL schema and start asking questions in minutes.
            </p>
            <Link to="/workspace">
              <Button size="lg" className="text-lg px-8">
                Launch App
              </Button>
            </Link>
          </div>
        </div>
      </main>

      {/* Footer */}
      <footer className="border-t border-border mt-24">
        <div className="container mx-auto px-6 py-8 text-center text-sm text-muted-foreground">
          © 2025 DB RAG Analytics. Powered by AI.
        </div>
      </footer>
    </div>
  );
};

export default Landing;
